jshint:
  image: gaiaadm/result-processing
  container_name: jshint-runner
  command: grunt jshint
node-unit:
  image: gaiaadm/result-processing
  container_name: unit-test-runner
  command: grunt unit
node-system:
  image: gaiaadm/result-processing
  container_name: system-test-runner
  command: /bin/bash -c "while ! nc -z rabbitmq 5672; do sleep 3; done && grunt system"
  environment:
    - AMQ_USER="admin"
    - AMQ_PASSWORD="admin"
    - AMQ_SERVER="rabbitmq:5672"
  links:
    - rabbitmq
rabbitmq:
  image: gaiaadm/rabbitmq
  environment:
    - RABBITMQ_PASS=admin
  expose:
    - 5672
